spring.application.name=feeltrack-backend

# Configuration accès à la base de données
spring.datasource.url=jdbc:mariadb://localhost:3307/sa
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# --------------------------------------------------------------------
# Hibernate dialect: informe Hibernate du type exact de base de données
# utilisée afin de générer un SQL compatible.
# - MariaDBDialect : pour MariaDB/MySQL
# - H2Dialect : pour la base H2 (souvent utilisée en tests)
# Référence doc Hibernate : https://docs.jboss.org/hibernate/orm/6.3/userguide/html_single/Hibernate_User_Guide.html#appendices-sql-dialects
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# --------------------------------------------------------------------
# Défère l'initialisation du datasource (data.sql / schema.sql)
# jusqu'à ce que Hibernate ait créé les tables. Utile pour :
# - Eviter les erreurs "table not found" si data.sql s'exécute trop tôt
# - Déploiements sur une vraie base (MariaDB, Postgres, etc.)
# En tests H2, on peut le désactiver car ddl-auto=create-drop s'occupe
# de créer les tables avant l’insertion des données.
# Référence Spring Boot : https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.spring.jpa.defer-datasource-initialization
spring.jpa.defer-datasource-initialization=true

# Désactivation des conversions automatiques de nommage de Spring Boot/Hibernate
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Préfixage globale des chemins de mon api
server.servlet.context-path=/api

# Liste des domaines autorisés
app.cors.allowed-origins=http://localhost:**


# ==== Configuration du logging ====

# Niveau global par défaut
logging.level.root=WARN
# Niveau global pour les affichages manuels
logging.level.ld.feeltrack_backend.config=INFO

# Forçage de l'affichage des messages console avec coloration syntaxique
spring.output.ansi.enabled=ALWAYS

# Spring Boot messages d’info au démarrage
logging.level.org.springframework.boot=INFO

# Hibernate : ne montrer que les erreurs critiques
logging.level.org.hibernate=ERROR
logging.level.com.zaxxer.hikari=WARN

# Désactiver logs SQL
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF


# ==== Actuator configuration ====

# Expose uniquement les endpoints utiles
management.endpoints.web.exposure.include=health

# Affiche les détails (DB, disk, etc.)
management.endpoint.health.show-details=always
